const url = 'http://localhost:8080'
const movies = '/api/movies'
const venues = '/api/venues'
const superAdmin = '/api/super-admin'
const projections = '/api/projections'
const genres = '/api/genres'
const cities = '/api/cities'
const currently = '/currently'
const upcoming = '/upcoming'
const searchCurrently = '/search-currently'
const searchUpcoming = '/search-upcoming'
const searchStatus = '/search-by-status'
const signin = '/api/auth/sign-in'
const signup = '/api/auth/sign-up'
const logout = '/logout'
const user = '/api/user'
const passwordReset = '/api/password-reset'
const reservation = '/api/tickets'

export { url, movies, venues, superAdmin, projections, genres, cities, currently, upcoming, searchCurrently, searchUpcoming, searchStatus, signin, signup, logout, user, passwordReset, reservation }
